### ISSUE TITLE
能够访问，但返回的页面为空白，求解决

### ISSUE THREAD

**Issue by Jones-Ding** [Dreamacro/clash-dashboard#108] opened 2022-11-08 11:26 UTC
问题截图:
![image](https://user-images.githubusercontent.com/85151087/200552114-f92e04d0-df97-48b6-b7de-05b51c0cb028.png)
文件路径结构:
![image](https://user-images.githubusercontent.com/85151087/200551493-2b9c7319-fb39-4f5e-b5b8-320a5f00e495.png)
config.yaml配置:
![image](https://user-images.githubusercontent.com/85151087/200551996-39d8c676-4d7e-4d6c-8ed8-5e0a810e6ffa.png)
控制台日志:
![image](https://user-images.githubusercontent.com/85151087/200552403-9d05f9c6-6ca7-41ac-8e33-32f4370e6e9e.png)

**Comment by Dreamacro** [comment] 2022-11-08 11:33
Duplicate of #46

**Closed by Dreamacro** 2022-11-08 11:33 UTC
